<?php

namespace Epsoftware\UserBundle\Repository;

/**
 * ImageUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageUserRepository extends \Doctrine\ORM\EntityRepository
{
}
