<?php

namespace Epsoftware\UserBundle\Repository;

/**
 * LoggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoggerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLogs($user_id = null)
    {
        $init = new \DateTime();
        $final = new \DateTime();
        date_sub($init, date_interval_create_from_date_string('60 days'));
        date_add($final, date_interval_create_from_date_string('1 days'));
        
        if($user_id):
            return $this->createQueryBuilder("l")
                ->where("l.user = :id and l.created BETWEEN :init AND :final")
                ->setParameter("id", $user_id)
                ->setParameter("init", $init->format("Y-m-d"))
                ->setParameter("final", $final->format("Y-m-d"))
                ->getQuery()    
                ->getResult();
        endif;
        return $this->createQueryBuilder("l")
                ->where("l.created BETWEEN :init AND :final")
                ->setParameter("init", $init->format("Y-m-d"))
                ->setParameter("final", $final->format("Y-m-d"))
                ->getQuery()
                ->getResult();
    }
}
