<?php

namespace Epsoftware\UserBundle\Repository;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findOneByRole($role)
    {
        return $this->createQueryBuilder("p")
                    ->where("p.role = :role")
                    ->setParameter("role", $role)
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
