<?php

namespace Epsoftware\UserBundle\Repository;

/**
 * TermsUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermsUserRepository extends \Doctrine\ORM\EntityRepository
{
    
}
