<?php

namespace Epsoftware\UserBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    private function findOneByUsernameOrEmail($user)
    {
        return $this->createQueryBuilder("u")
                    ->where("u.username = :username or u.email = :email")
                    ->setParameter("username", $user)
                    ->setParameter("email", $user)
                    ->getQuery()
                    ->getOneOrNullResult();
    }

    public function loadUserByUsername($username)
    {
        $user = $this->findOneByUsernameOrEmail($username);
        
        if(!$user):
            throw new UsernameNotFoundException("Login ou senha inválidos.");
        endif;
        
        return $user;
    }

    public function refreshUser(AdvancedUserInterface $user)
    {
        $class = get_class($user);
        
        if(!$this->supportsClass($class)):
            throw new UnsupportedUserException("Erro. Classe não suportada");
        endif;
        
        return $this->findOneByUsernameOrEmail($user->getUsername());
    }

    public function supportsClass($class)
    {
        return $this->getEntityName() == $class || is_subclass_of($class, $this->getEntityName());
    }
}
