address:
    resource: "@AddressBundle/Controller/"
    type:     annotation
    prefix:   /

mensageria:
    resource: "@MensageriaBundle/Controller/"
    type:     annotation
    prefix:   /

perfil:
    resource: "@PerfilBundle/Controller/"
    type:     annotation
    prefix:   /

success:
    resource: "@SuccessBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

institucional:
    resource: "@InstitucionalBundle/Controller/"
    type:     annotation
    prefix:   /

menu:
    resource: "@MenuBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

