<?php

namespace Epsoftware\MenuBundle\Repository;

/**
 * FirstMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirstMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
