<?php

namespace Epsoftware\MenuBundle\Repository;

/**
 * SecondMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
