<?php

namespace Epsoftware\MenuBundle\Repository;

/**
 * ThirdMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThirdMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
