<?php

namespace Epsoftware\PerfilBundle\Repository;

/**
 * ProfissaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfissaoRepository extends \Doctrine\ORM\EntityRepository
{
}
