services:
#    address.example:
#        class: Epsoftware\AddressBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    epsoftware.twig.list.address:
        class: Epsoftware\AddressBundle\Twig\ListAddress
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [setTwigEnvironment, ["@Twig"]]
        public: false
        tags: 
            - { name: twig.extension }